---

- hosts: localhost
  become: true 
 
  tasks: 
   - name: "installing lamp"
     yum: name={{item}} state=installed disable_gpg_check=yes
     register: lampstatus
     with_items:
       - httpd
       - php
       - mariadb
       - mariadb-server
       - php-mysql
    
   - name: "starting lamp services"
     service: name={{item}} enabled=yes state=started
     when: lampstatus|success
     with_items:
        - httpd
        - mariadb
